version: '3'

#expose the service in the container is not accessible from outside Docker,
#but from inside other Docker containers
#on-failure restart container if exit code indicate an error
#volumes defines mount host paths or named volumes that MUST be accessible by service containers. 
services:
  mariadb:
    container_name: mariadb
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes: 
      - mariadb:/var/lib/mysql
    networks:
      - inception
    expose:
      - "3306"
    restart: on-failure 
    init: true

#depends MUST create and removes services in dependency order 
  wordpress:
    container_name: wordpress
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on: 
      - mariadb
    restart: on-failure
    expose: 
      - "9000"
    init: true

  nginx:
    container_name: nginx 
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: on-failure
    init: true

 
#to respect the subject and obtain a name volume with path changed 
#we use this local driver bind mount
#driver_opts options are same as "mount" -mount(8) linux man page-
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jholl/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jholl/data/mariadb'

#bridge cause we want some interaction between our containers in the same network
#and in the same time we block interaction with containers from other networks
#we specify it cause we dont want the default bridge but the user-defined bridge
networks:
    inception:
      driver: bridge
